services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: false
        tags:
            - { name: twig.extension }